spring:

  application:
    name: search-service

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    virtual-host: outbox

rabbitmq:
  exchange: search-index
  queue: search-index-queue
  routing-key: search.update.ticket
  dlq:
    exchange: search-index-dlx
    queue: search-index-dlq
    routing-key: search.update.ticket.dead


logging:
  level:
    org.springframework.data.elasticsearch.core: DEBUG
    org.apache.http: DEBUG
